#!/usr/bin/env python3
"""
Idempotent Lakebase (Autoscaling Postgres) bootstrap for RevisioFitxers.

Ensures a Lakebase project exists, discovers its branch/endpoint/database, applies the
state-store schema (sql/lakebase_schema.sql), and prints the connection facts other steps
(the classify pipeline task, the app) need. Safe to run repeatedly.

Because Lakebase Autoscaling is NOT yet a first-class DAB resource (the bundle's
database_instances/synced_database_tables map to the Provisioned API), this runs as a
`setup.sh` step before `bundle deploy` — that's what keeps the whole project one-click on
a fresh workspace (spec build-plan Phase 2.1 / one-click requirement).

Usage:
  python3 scripts/ensure_lakebase.py --profile <profile> [--project revisiofitxers]
                                     [--write-config resources/lakebase.generated.yml]

Prereqs: databricks-sdk >= 0.81, psycopg. CLI authenticated for <profile>.
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

from databricks.sdk import WorkspaceClient

SCHEMA_SQL = Path(__file__).resolve().parent.parent / "sql" / "lakebase_schema.sql"


def ensure_project(w: WorkspaceClient, project_id: str, display_name: str, profile: str) -> None:
    """Create the project via the CLI (it waits for DONE) if it doesn't already exist."""
    try:
        w.postgres.get_project(f"projects/{project_id}")
        print(f"Lakebase project '{project_id}' already exists.")
        return
    except Exception:  # noqa: BLE001 — not-found or transient; try to create
        pass
    print(f"Creating Lakebase project '{project_id}' (this can take a few minutes)...")
    body = json.dumps({"spec": {"display_name": display_name}})
    subprocess.run(
        ["databricks", "postgres", "create-project", project_id, "--json", body, "--profile", profile],
        check=True,
    )
    print(f"Lakebase project '{project_id}' is READY.")


def discover(w: WorkspaceClient, project_id: str) -> dict:
    branch = list(w.postgres.list_branches(f"projects/{project_id}"))[0]
    endpoint = list(w.postgres.list_endpoints(branch.name))[0]
    database = list(w.postgres.list_databases(branch.name))[0]
    host = endpoint.status.hosts.host
    pg_dbname = getattr(database.status, "postgres_database", None) or "databricks_postgres"
    return {
        "project_id": project_id,
        "branch": branch.name,
        "endpoint": endpoint.name,
        "database": database.name,
        "host": host,
        "pg_database": pg_dbname,
    }


def apply_schema(w: WorkspaceClient, facts: dict) -> None:
    import psycopg

    cred = w.postgres.generate_database_credential(facts["endpoint"])
    token = cred.token
    me = w.current_user.me()
    user = me.user_name
    dsn = (
        f"host={facts['host']} dbname={facts['pg_database']} "
        f"user={user} password={token} sslmode=require"
    )
    ddl = SCHEMA_SQL.read_text(encoding="utf-8")
    print(f"Applying schema from {SCHEMA_SQL.name} to {facts['host']}/{facts['pg_database']} ...")
    with psycopg.connect(dsn, autocommit=True) as conn:
        with conn.cursor() as cur:
            cur.execute(ddl)
            cur.execute("SELECT count(*) FROM revisiofitxers.taxonomy_categories")
            n = cur.fetchone()[0]
    print(f"Schema applied. taxonomy_categories rows: {n}")


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--profile", default="DEFAULT")
    p.add_argument("--project", default="revisiofitxers")
    p.add_argument("--display-name", default="RevisioFitxers state store")
    p.add_argument("--write-config", default=None, help="Write discovered facts as a DAB vars YAML")
    p.add_argument("--json-out", default=None, help="Also write facts as JSON to this path")
    args = p.parse_args()

    w = WorkspaceClient(profile=args.profile)
    ensure_project(w, args.project, args.display_name, args.profile)
    facts = discover(w, args.project)
    apply_schema(w, facts)

    print("\nLakebase connection facts:")
    print(json.dumps(facts, indent=2))

    if args.json_out:
        Path(args.json_out).write_text(json.dumps(facts, indent=2), encoding="utf-8")
    if args.write_config:
        # Emit a DAB variable-values file the bundle can consume via --var-file style include.
        cfg = (
            "# Auto-generated by ensure_lakebase.py — do not edit by hand.\n"
            "variables:\n"
            f"  lakebase_host:\n    default: \"{facts['host']}\"\n"
            f"  lakebase_pg_database:\n    default: \"{facts['pg_database']}\"\n"
            f"  lakebase_endpoint:\n    default: \"{facts['endpoint']}\"\n"
            f"  lakebase_project:\n    default: \"{facts['project_id']}\"\n"
        )
        Path(args.write_config).write_text(cfg, encoding="utf-8")
        print(f"Wrote DAB vars to {args.write_config}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
